services:
    _defaults:
        public: true
        autowire: true

    Migrify\LatteToTwig\:
        resource: '../src'
        exclude:
            - '../src/Contract'
            - '../src/Exception'
            - '../src/HttpKernel/LatteToTwigKernel.php'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
    Symplify\SmartFileSystem\SmartFileSystem: null
